### ISSUE TITLE
Website migration

### ISSUE THREAD

**Issue by dontlaugh** [croservices/cro-website#8]
Hey there, we are coordinating website migration to raku community servers.

We're going to coordinate the work here (private to community github)
https://github.com/Raku/infra/issues/51

Apologies for sending messages in 5 different places, but Liz said your cro.services cert is about to expire in less than a week. If you could renew it before then it would help a LOT.

Thank you <3

**Comment by jnthn** [comment]
> Apologies for sending messages in 5 different places, but Liz said your cro.services cert is about to expire in less than a week. If you could renew it before then it would help a LOT.

It's meant to auto-renew, but it's somehow flaky. Triggered a renewal manually; it'll be good through July now, by which point I expect operations to have been taken over by the Raku community.

**Comment by dontlaugh** [comment]
Thank you!
